service: chess-game-review

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-2'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  demo:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: img